### ISSUE TITLE
Create Modpack

### ISSUE THREAD

**Issue by barral69gaming** [KuBino122/Create-Expanded#1]
You have put 4 different shaderpacks into this modpack. However, you have NOT put in a shader support such as Irish or Optifine. But, if a user manually installs a shader support, the mod-Create is now invalid due to version conflicts. Please fix this.

**Comment by barral69gaming** [comment]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Remove mod 'Create Crafts & Additions' (createaddition) 0.9.0 (C:\Users\barra\AppData\Roaming\com.modrinth.theseus\profiles\Create Expanded\mods\createaddition-fabric+1.20.1-0.9.0.jar).
	 - Replace mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 with version 0.5.1- or later that is compatible with:
		 - sodium 0.5.3
More details:
	 - Mod 'Create' (create) 0.5.1-d-build.1161+mc1.20.1 is incompatible with version 0.5.0 or later of mod 'Sodium' (sodium), but a matching version is present: 0.5.3!
	 - Mod 'Fastload Fabric-api Forwarding' (fastload_fapi_forward) 1.0.2 requires version 1.19.3 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by KuBino122** [comment]
Resolved, there is no compatibility in current version for the shaders so i removed them
